#guess if the face displayed is a real person or style-GAN generated
from PIL import Image
import os
import sys
import random
import time


def realOrFake():
    correct = 0
    total = -1
    while True:
        os.chdir('/Users/wyattmarshall/Documents/programs/faces')
        total += 1
        os.system('cls' if os.name == 'nt' else 'clear')
        print('\n\n\n')
        print("Is this person real, or were they generated by style-GAN?\n")
        if total != 0:
            print("Currently " + str(correct) + " out of " + str(total) + " guesses have been correct (" + str(100 * (correct/total)) + "%).\n")
        print("If you think the person is real, enter 'r'. If you think the person is fake, enter 'f'.\n")
        while True:
            start = input("Enter 'q' to quit, or press return to play: ")
            if start == 'q' or start == '':
                break
    
        print('')

        if start == 'q':
            print("Thanks for playing!")
            print("\n")
            sys.exit()
        else:
            i = random.randint(0, 1)
            if i == 1:
                os.chdir('real/')
            else:
                os.chdir('fake/')
            j = random.randint(0, 4999)
            im = Image.open(str(j) + ".jpg")
            im.show()
            print("Is this image (r)eal or (f)ake?")
            print("(click back on this window to enter your answer)")
            print('')
            while True:
                ans = input("Answer: ")
                if ans == 'r' or ans == 'f':
                    break
                else:
                    print("Enter 'r' for real or 'f' for fake.")
            print('')
            if ans == 'r' and i == 1:
                print("Correct! This person exists.")
                correct += 1
            elif ans == 'r' and i == 0:
                print("Incorrect! This person does not exist.")
            elif ans == 'f' and i == 0:
                print("Correct! This person does not exist.")
                correct += 1
            else:
                print("Incorrect! This person exists.")
            
            while True:
                playagain = input("Close the image and then press enter to play again.\n")
                if playagain == '':
                    break
                elif playagain == 'q':
                    sys.exit()

realOrFake()